voxel_size: [0.1, 0.1, 0.2]
point_cloud_range: [-75.0, -75.0, -8.0, 75.0, 75.0, 0.0]

model:
  encoders:
    lidar:
      voxelize:
        max_num_points: 10
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        type: SparseEncoder
        in_channels: 5
        sparse_shape: [1500, 1500, 41]
        output_channels: 128
        order:
          - conv
          - norm
          - act
        encoder_channels:
          - [16, 16, 32]
          - [32, 32, 64]
          - [64, 64, 128]
          - [128, 128]
        encoder_paddings:
          - [0, 0, 1]
          - [0, 0, 1]
          - [0, 0, [1, 1, 0]]
          - [0, 0]
        block_type: basicblock
  heads:
    object:
      train_cfg:
        grid_size: [1500, 1500, 41]
      test_cfg:
        grid_size: [1500, 1500, 41]