voxel_size: [0.1, 0.1, 0.2]
point_cloud_range: [-20.0, -80.0, -10.0, 140.0, 80.0, 0.0]

optimizer:
  lr: 1.0e-4

data:
  samples_per_gpu: 6
  workers_per_gpu: 6

model:
  encoders:
    lidar:
      voxelize:
        max_num_points: 10
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        type: SparseEncoder
        in_channels: 4
        sparse_shape: [1600, 1600, 51]
        output_channels: 128
        order:
          - conv
          - norm
          - act
        encoder_channels:
          - [16, 16, 32]
          - [32, 32, 64]
          - [64, 64, 128]
          - [128, 128]
        encoder_paddings:
          - [0, 0, 1]
          - [0, 0, 1]
          - [0, 0, [1, 1, 0]]
          - [0, 0]
        block_type: basicblock
  heads:
    object:
      train_cfg:
        grid_size: [1600, 1600, 51]
      test_cfg:
        grid_size: [1600, 1600, 51]