augment3d:
  scale: [0.95, 1.05]
  rotate: [-0.3925, 0.3925]
  translate: 0

model:
  encoders:
    lidar: null
    camera:
      vtransform:
        type: LSSTransform
        image_size: ${image_size}
        xbound: [-25.0, 125.0, 0.4]
        ybound: [-75.0, 75.0, 0.4]
        zbound: [-12.0, 8.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
  heads:
    object:
      test_cfg:
        nms_type:
          - circle
          - rotate
          - rotate
          - rotate
          - rotate
          - rotate
        nms_scale:
          - [1.0]
          - [1.0]
          - [1.0]
          - [1.0, 1.0]
          - [1.0, 1.0]
          - [1.0]

lr_config: null
