model:
  type: TBEVFusion
  encoders: null
  fuser: null
  temporal: null
  heads:
    map: null

temporal_mode: true
val_online_mode: true
test_online_mode: true

temporal_aware_gt_paste: true
apply_same_aug_to_seq: true
