point_cloud_range: [-6.0, -128.0, -3.0, 250.0, 128.0, 13.0]
post_center_range: [-11.0, -132.0, -5.0, 255.0, 132.0, 15.0]

voxel_size: [0.16, 0.16, 0.4]
grid_size: [1600, 1600, 41]

queue_length: 3
temporal_cache_length: 3
queue_range_threshold: 1

deterministic: True

voxel_max_points: 15
voxel_max_voxels: [200000, 200000]

samples_per_gpu: 6
workers_per_gpu: 6

max_epochs: 4

augment_gt_paste:
  max_epoch: 3
  apply_same_aug_to_seq: true
  sampler:
    reduce_points_by_distance:
      prob: 0.5

optimizer:
  type: AdamW
  lr: 6.6e-05
  weight_decay: 0.01
  paramwise_cfg:
    custom_keys:
      encoders.lidar.backbone:
        lr_mult: 0.0

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3

optimizer_config:
  grad_clip:
    max_norm: 25
    norm_type: 2

model:
  encoders:
    lidar:
      voxelize:
        max_num_points: ${voxel_max_points}
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: ${voxel_max_voxels}
      backbone:
        type: SparseEncoder
        in_channels: ${use_dim}
        sparse_shape: ${grid_size}
        output_channels: 128
        order:
          - conv
          - norm
          - act
        encoder_channels:
          - [16, 16, 32]
          - [32, 32, 64]
          - [64, 64, 128]
          - [128, 128]
        encoder_paddings:
          - [0, 0, 1]
          - [0, 0, 1]
          - [0, 0, [1, 1, 0]]
          - [0, 0]
        block_type: basicblock
