point_cloud_range: [-6.0, -128.0, -3.0, 250.0, 128.0, 13.0]
post_center_range: [-11.0, -132.0, -5.0, 255.0, 132.0, 15.0]

image_size: [256, 704]
voxel_size: [0.16, 0.16, 0.4]
grid_size: [1600, 1600, 1]

find_unused_parameters: true

queue_length: 3
temporal_cache_length: 3
queue_range_threshold: 1

xbound: ${[point_cloud_range[0], point_cloud_range[3], voxel_size[0] * 4]}
ybound: ${[point_cloud_range[1], point_cloud_range[4], voxel_size[1] * 4]}
zbound: ${[point_cloud_range[2], point_cloud_range[5], point_cloud_range[5] - point_cloud_range[2]]}
dbound: [1.0, 240.0, 2.0]

out_size_factor: 8
score_threshold: 0.05
nms_threshold: 0.2

samples_per_gpu: 6
workers_per_gpu: 6

max_epochs: 4

optimizer:
  type: AdamW
  lr: 6.6e-05
  weight_decay: 0.01
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0
      relative_position_bias_table:
        decay_mult: 0
      encoders.camera.backbone:
        lr_mult: 0.0 # freezed

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3

optimizer_config:
  grad_clip:
    max_norm: 25
    norm_type: 2

augment2d:
  resize: [[0.36, 0.44], [0.4, 0.4]]
  bot_pct_lim: [[0.3, 0.5], [0.4, 0.4]]
  rotate: [-5.4, 5.4]
  gridmask:
    prob: 0.0
    fixed_prob: true
    max_epochs: 17

augment3d:
  scale: [0.95, 1.05]
  rotate: [-0.05, 0.05]
  translate: 0

model:
  encoders:
    camera:
      backbone:
        type: SwinTransformer
        embed_dims: 96
        depths: [2, 2, 6, 2]
        num_heads: [3, 6, 12, 24]
        window_size: 7
        mlp_ratio: 4
        qkv_bias: true
        qk_scale: null
        drop_rate: 0.
        attn_drop_rate: 0.
        drop_path_rate: 0.2
        patch_norm: true
        out_indices: [1, 2, 3]
        with_cp: false
        convert_weights: true
        init_cfg:
          type: Pretrained
          checkpoint: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth
      neck:
        type: GeneralizedLSSFPN
        in_channels: [192, 384, 768]
        out_channels: 256
        start_level: 0
        num_outs: 3
        norm_cfg:
          type: BN2d
          requires_grad: true
        act_cfg:
          type: ReLU
          inplace: true
        upsample_cfg:
          mode: bilinear
          align_corners: false
      vtransform:
        type: DepthLSSTransform
        image_size: ${image_size}
        in_channels: 256
        out_channels: 80
        feature_size: ${[image_size[0] // 8, image_size[1] // 8]}
        xbound: ${xbound}
        ybound: ${ybound}
        zbound: ${zbound}
        dbound: ${dbound}
        downsample: 2
  decoder:
    backbone:
      type: GeneralizedResNet
      in_channels: 80
      blocks:
        - [2, 128, 2]
        - [2, 256, 2]
        - [2, 512, 1]
    neck:
      type: LSSFPN
      in_indices: [-1, 0]
      in_channels: [512, 128]
      out_channels: 256
      scale_factor: 2
