seed: 1337
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 3

log_config:
  interval: 50
  hooks:
    - type: TextLoggerHook
    - type: TensorboardLoggerHook

load_from: null
resume_from: null

cudnn_benchmark: false
fp16:
  loss_scale:
    growth_interval: 2000

data:
  samples_per_gpu: ${samples_per_gpu}
  workers_per_gpu: ${workers_per_gpu}

max_epochs: 20
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}
