point_cloud_range: [-6.0, -128.0, -3.0, 250.0, 128.0, 13.0]
post_center_range: [-11.0, -132.0, -5.0, 255.0, 132.0, 15.0]

voxel_size: [0.125, 0.125, 0.4]
grid_size: [2048, 2048, 41]

voxel_max_points: 15
voxel_max_voxels: [200000, 200000]
out_size_factor: 8

samples_per_gpu: 6
workers_per_gpu: 6

max_epochs: 20
gt_paste_stop_epoch: 15

optimizer:
  type: AdamW
  lr: 2.0e-5
  weight_decay: 0.01

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

lr_config:
  cyclic_times: 1
  policy: cyclic
  step_ratio_up: 0.4

optimizer_config:
  grad_clip:
    max_norm: 25
    norm_type: 2

augment3d:
  scale: [0.9, 1.1]
  rotate: [-0.78539816, 0.78539816]
  translate: 0.5

model:
  encoders:
    lidar:
      voxelize:
        max_num_points: ${voxel_max_points}
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: ${voxel_max_voxels}
      backbone:
        type: SparseEncoder
        in_channels: ${use_dim}
        sparse_shape: ${grid_size}
        output_channels: 128
        order:
          - conv
          - norm
          - act
        encoder_channels:
          - [16, 16, 32]
          - [32, 32, 64]
          - [64, 64, 128]
          - [128, 128]
        encoder_paddings:
          - [0, 0, 1]
          - [0, 0, 1]
          - [0, 0, [1, 1, 0]]
          - [0, 0]
        block_type: basicblock
