dataset_type: OSDAR23Dataset
dataset_root: data/osdar23-bevfusion/

reduce_beams: 32
load_dim: 6
use_dim: 4 # x, y, z, intensity, timestamp, sensor_idx
load_augmented: null

image_size: [256, 704] # default
out_size_factor: 8 # default
score_threshold: 0.0 # default

apply_same_aug_to_seq: false # default, apply same augmentation to all frames in a temporal sequence

queue_length: null # default, None means no temporal
queue_range_threshold: 0 # default
test_queue_range_threshold: 0 # default

augment2d: # default
  resize: [[0.38, 0.55], [0.48, 0.48]]
  bot_pct_lim: [[0.6, 0.7], [0.65, 0.65]]
  rotate: [-5.4, 5.4]
  gridmask:
    prob: 0.0
    fixed_prob: true
    max_epochs: -1

augment3d: # default
  scale: [0.9, 1.1]
  rotate: [-0.2, 0.2]
  translate: 0.25

augment_gt_paste: # default
  apply_same_aug_to_seq: false
  apply_collision_check: true
  apply_temporal_forward: true
  max_epoch: -1
  sample_groups:
    lidar__cuboid__person: 7
    lidar__cuboid__catenary_pole: 4
    lidar__cuboid__signal_pole: 4
    lidar__cuboid__road_vehicle: 3
    lidar__cuboid__buffer_stop: 2
  sampler:
    rate: 1.0
    reduce_points_by_distance:
      prob: 0.0
      distance_threshold: 250
      max_ratio: 0.6
    filter_by_difficulty: [-1]
    filter_by_min_points:
      lidar__cuboid__person: 5
      lidar__cuboid__catenary_pole: 5
      lidar__cuboid__signal_pole: 5
      lidar__cuboid__road_vehicle: 5
      lidar__cuboid__buffer_stop: 5
    cls_trans_lim: null
    cls_rot_lim: null

no_classes: 5
object_classes:
  - lidar__cuboid__person
  - lidar__cuboid__catenary_pole
  - lidar__cuboid__signal_pole
  - lidar__cuboid__road_vehicle
  - lidar__cuboid__buffer_stop

input_modality:
  use_lidar: true
  use_camera: true
  use_radar: false
  use_map: false
  use_external: false

train_pipeline:
  - type: LoadTemporalFiles
    queue_length: ${queue_length}
    queue_range_threshold: ${queue_range_threshold}
    load_images_vars:
      to_float32: true
    load_points_vars:
      coord_type: LIDAR
      load_dim: ${load_dim}
      use_dim: ${use_dim}
      reduce_beams: ${reduce_beams}
      load_augmented: ${load_augmented}
    load_annotations_vars:
      with_bbox_3d: true
      with_label_3d: true
      with_attr_label: False
  - type: ObjectPaste
    stop_epoch: ${augment_gt_paste.max_epoch}
    apply_collision_check: ${augment_gt_paste.apply_collision_check}
    apply_same_aug_to_seq: ${augment_gt_paste.apply_same_aug_to_seq}
    apply_temporal_forward: ${augment_gt_paste.apply_temporal_forward}
    db_sampler:
      dataset_root: ${dataset_root}
      reduce_points_by_distance: ${augment_gt_paste.sampler.reduce_points_by_distance}
      cls_rot_lim: ${augment_gt_paste.sampler.cls_rot_lim}
      cls_trans_lim: ${augment_gt_paste.sampler.cls_rot_lim}
      info_path: ${dataset_root + "osdar23_dbinfos_train.pkl"}
      rate: ${augment_gt_paste.sampler.rate}
      prepare:
        filter_by_difficulty: ${augment_gt_paste.sampler.filter_by_difficulty}
        filter_by_min_points: ${augment_gt_paste.sampler.filter_by_min_points}
      classes: ${object_classes}
      sample_groups: ${augment_gt_paste.sample_groups}
      points_loader:
        type: LoadPointsFromFile
        coord_type: LIDAR
        load_dim: ${load_dim}
        use_dim: ${use_dim}
        reduce_beams: ${reduce_beams}
  - type: ImageAug3D
    final_dim: ${image_size}
    resize_lim: ${augment2d.resize[0]}
    bot_pct_lim: ${augment2d.bot_pct_lim[0]}
    rot_lim: ${augment2d.rotate}
    rand_flip: true
    is_train: true
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: GlobalRotScaleTrans
    resize_lim: ${augment3d.scale}
    rot_lim: ${augment3d.rotate}
    trans_lim: ${augment3d.translate}
    is_train: true
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: RandomFlip3D
    flip_horizontal: true
    flip_vertical: false
    is_train: true
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: PointsRangeFilter
    point_cloud_range: ${point_cloud_range}
  - type: ObjectRangeFilter
    point_cloud_range: ${point_cloud_range}
  - type: ObjectNameFilter
    classes: ${object_classes}
  - type: ImageNormalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: GridMask
    use_h: true
    use_w: true
    max_epoch: ${augment2d.gridmask.max_epochs}
    rotate: 1
    offset: false
    ratio: 0.5
    mode: 1
    prob: ${augment2d.gridmask.prob}
    fixed_prob: ${augment2d.gridmask.fixed_prob}
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: PointShuffle
  - type: DefaultFormatBundle3D
    classes: ${object_classes}
  - type: Collect3D
    keys:
      - img
      - points
      - gt_bboxes_3d
      - gt_labels_3d
    meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix

test_pipeline:
  - type: LoadTemporalFiles
    queue_length: ${queue_length}
    queue_range_threshold: ${test_queue_range_threshold}
    load_images_vars:
      to_float32: true
    load_points_vars:
      coord_type: LIDAR
      load_dim: ${load_dim}
      use_dim: ${use_dim}
      reduce_beams: ${reduce_beams}
      load_augmented: ${load_augmented}
    load_annotations_vars:
      with_bbox_3d: true
      with_label_3d: true
      with_attr_label: False
  - type: ImageAug3D
    final_dim: ${image_size}
    resize_lim: ${augment2d.resize[1]}
    bot_pct_lim: ${augment2d.bot_pct_lim[1]}
    rot_lim: [0.0, 0.0]
    rand_flip: false
    is_train: false
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: GlobalRotScaleTrans
    resize_lim: [1.0, 1.0]
    rot_lim: [0.0, 0.0]
    trans_lim: 0.0
    is_train: false
    apply_same_aug_to_seq: ${apply_same_aug_to_seq}
  - type: PointsRangeFilter
    point_cloud_range: ${point_cloud_range}
  - type: ImageNormalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: DefaultFormatBundle3D
    classes: ${object_classes}
  - type: Collect3D
    keys:
      - img
      - points
      - gt_bboxes_3d
      - gt_labels_3d
    meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix

evaluation:
  interval: 1
  pipeline: ${test_pipeline}

data:
  train:
    type: CBGSDataset
    temporal: ${temporal_mode}
    dataset:
      type: ${dataset_type}
      dataset_root: ${dataset_root}
      ann_file: ${dataset_root + "osdar23_infos_train.pkl"}
      pipeline: ${train_pipeline}
      object_classes: ${object_classes}
      modality: ${input_modality}
      test_mode: false
      online: false
      queue_length: ${queue_length}
      queue_range_threshold: ${queue_range_threshold}
      use_valid_flag: true
      box_type_3d: LiDAR
  val:
    type: ${dataset_type}
    dataset_root: ${dataset_root}
    ann_file: ${dataset_root + "osdar23_infos_val.pkl"}
    pipeline: ${test_pipeline}
    object_classes: ${object_classes}
    modality: ${input_modality}
    test_mode: true
    online: ${val_online_mode}
    queue_length: ${queue_length}
    queue_range_threshold: ${test_queue_range_threshold}
    box_type_3d: LiDAR
    eval_point_cloud_range: ${point_cloud_range}
  test:
    type: ${dataset_type}
    dataset_root: ${dataset_root}
    ann_file: ${dataset_root + "osdar23_infos_val.pkl"}
    pipeline: ${test_pipeline}
    object_classes: ${object_classes}
    modality: ${input_modality}
    test_mode: true
    online: ${test_online_mode}
    queue_length: ${queue_length}
    queue_range_threshold: ${test_queue_range_threshold}
    box_type_3d: LiDAR
    eval_point_cloud_range: ${point_cloud_range}
